### ISSUE TITLE
怎么集成到reactjs？

### ISSUE THREAD

**Issue by chat491231702** [a-ke/timescale#3]
已尝试集成进基于react构建的应用，但是发现timescale里面有不少操作原生dom节点的代码，执行时报错

**Comment by chat491231702** [comment]
已通过将timescale目录放置在public目录，然后在react组件中通过如下动态插入script引入解决（使用script引入的方式）
componentDidMount() {
    let script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = './timescale/timescale.min.js';
    script.onload = this.initTimeline
    document.body.appendChild(script);
  }
===========================================
希望高手告诉我如何通过readme中的“import引入”方式解决！

**Comment by chat491231702** [comment]
已通过将timescale目录放置在public目录，然后在react组件中通过如下动态插入script引入解决（使用script引入的方式）
===========================================
componentDidMount() {
    let script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = './timescale/timescale.min.js';
    script.onload = this.initTimeline
    document.body.appendChild(script);
  }
===========================================
希望高手告诉我如何通过readme中的“import引入”方式解决！

**Comment by a-ke** [comment]
使用import方式引入脚本就不需要动态创建script标签了。只需要在react或vue的js入口文件中按第二种方式编写，引入必需的三个文件即可。
